### ISSUE TITLE
Add custom crash report activity

### ISSUE THREAD

**Issue by divadsn** [Deletescape-Media/Lawnchair#1478]
The current way of storing crash logs is unreliable and not everyone is able to run Scoop without root or have access to a PC to get the stack trace using logcat. I was already doing some work, but lost focus due to school and recent changes in source code.

### Roadmap
- [x] Add CAOC library
- [x] Kang my crash reporter from my app
- [ ] Fix UI layout and remove old handler
- [ ] Support dogbin upload

**Comment by nyancrimew** [comment]
Important: Also add an option to default the screen to not show again. Otherwise people might get annoyed by it.
